apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngnix
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ngnix 
  template:
    metadata:
      labels:
        app: ngnix
    spec:
      containers:
      - name: ngnix
        image: arm32v7/nginx
        ports:
        - containerPort: 80
