apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ngnix
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: ngnix
    spec:
      containers:
      - name: ngnix
        image: arm32v7/nginx
        ports:
        - containerPort: 80