apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{.Values.mainLabel}}
  template:
    metadata:
      labels:
        app: {{.Values.mainLabel}}
    spec:
      containers:
      - name: nginx
        image: {{.Values.image.tag}}
        ports:
        - containerPort: 80
