apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.name}}
spec:
  selector:
    app: {{.Values.mainLabel}}
  ports:
  - name: main
    protocol: TCP
    port: {{.Values.service.externalPort}}
    targetPort: 80
